// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigerService is an autogenerated mock type for the ConfigerService type
type ConfigerService struct {
	mock.Mock
}

type ConfigerService_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigerService) EXPECT() *ConfigerService_Expecter {
	return &ConfigerService_Expecter{mock: &_m.Mock}
}

// GetAddressServerURL provides a mock function with given fields:
func (_m *ConfigerService) GetAddressServerURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ConfigerService_GetAddressServerURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddressServerURL'
type ConfigerService_GetAddressServerURL_Call struct {
	*mock.Call
}

// GetAddressServerURL is a helper method to define mock.On call
func (_e *ConfigerService_Expecter) GetAddressServerURL() *ConfigerService_GetAddressServerURL_Call {
	return &ConfigerService_GetAddressServerURL_Call{Call: _e.mock.On("GetAddressServerURL")}
}

func (_c *ConfigerService_GetAddressServerURL_Call) Run(run func()) *ConfigerService_GetAddressServerURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigerService_GetAddressServerURL_Call) Return(_a0 string) *ConfigerService_GetAddressServerURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigerService_GetAddressServerURL_Call) RunAndReturn(run func() string) *ConfigerService_GetAddressServerURL_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewConfigerService interface {
	mock.TestingT
	Cleanup(func())
}

// NewConfigerService creates a new instance of ConfigerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConfigerService(t mockConstructorTestingTNewConfigerService) *ConfigerService {
	mock := &ConfigerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
